const SHOP_DATA = [
  {
    title: "Znaki ostrzegawcze",
    items: [
      {
        id: 1,
        numer_znaku: "A-1",
        name: "Niebezpieczny zakręt w prawo",
        obraz: "/images/ostrzegawcze/A-1.png",
        price: 150,
      },
      {
        id: 2,
        numer_znaku: "A-2",
        name: "Niebezpieczny zakręt w lewo",
        obraz: "/images/ostrzegawcze/A-2.png",
        price: 150,
      },
      {
        id: 3,
        numer_znaku: "A-3",
        name: "Niebezpieczne zakręty – pierwszy w prawo",
        obraz: "/images/ostrzegawcze/A-3.png",
        price: 150,
      },
      {
        id: 4,
        numer_znaku: "A-4",
        name: "Niebezpieczne zakręty – pierwszy w lewo",
        obraz: "/images/ostrzegawcze/A-4.png",
        price: 150,
      },
      {
        id: 5,
        numer_znaku: "A-5",
        name: "Skrzyżowanie dróg",
        obraz: "/images/ostrzegawcze/A-5.png",
        price: 150,
      },
      {
        id: 6,
        numer_znaku: "A-6a",
        name: "Skrzyżowanie z drogą podporządkowaną występującą po obu stronach",
        obraz: "/images/ostrzegawcze/A-6a.png",
        price: 150,
      },
      {
        id: 7,
        numer_znaku: "A-6b",
        name: "Skrzyżowanie z drogą podporządkowaną występującą po prawej stronie",
        obraz: "/images/ostrzegawcze/A-6b.png",
        price: 150,
      },
      {
        id: 8,
        numer_znaku: "A-6c",
        name: "Skrzyżowanie z drogą podporządkowaną występującą po lewej stronie",
        obraz: "/images/ostrzegawcze/A-6b.png",
        price: 150,
      },
      {
        id: 9,
        numer_znaku: "A-6d",
        name: "Wlot drogi jednokierunkowej z prawej strony",
        obraz: "/images/ostrzegawcze/A-6d.png",
        price: 150,
      },
      {
        id: 10,
        numer_znaku: "A-6e",
        name: "Wlot drogi jednokierunkowej z lewej strony",
        obraz: "/images/ostrzegawcze/A-6e.png",
        price: 150,
      },
      {
        id: 11,
        numer_znaku: "A-7",
        name: "Ustąp pierwszeństwa",
        obraz: "/images/ostrzegawcze/A-7.png",
        price: 150,
      },
      {
        id: 12,
        numer_znaku: "A-8",
        name: "Skrzyżowanie o ruchu okrężnym",
        obraz: "/images/ostrzegawcze/A-8.png",
        price: 150,
      },
      {
        id: 13,
        numer_znaku: "A-9",
        name: "Przejazd kolejowy z zaporami",
        obraz: "/images/ostrzegawcze/A-9.png",
        price: 150,
      },
      {
        id: 14,
        numer_znaku: "A-10",
        name: "Przejazd kolejowy bez zapór",
        obraz: "/images/ostrzegawcze/A-10.png",
        price: 150,
      },
      {
        id: 15,
        numer_znaku: "A-11",
        name: "Znak ostrzegający o nierównej drodze",
        obraz: "/images/ostrzegawcze/A-11.png",
        price: 150,
      },
      {
        id: 16,
        numer_znaku: "A-11a",
        name: "Znak ostrzegający o progu zwalniającym",
        obraz: "/images/ostrzegawcze/A-11a.png",
        price: 150,
      },
      {
        id: 17,
        numer_znaku: "A-12a",
        name: "Zwężenie jezdni – obustronne",
        obraz: "/images/ostrzegawcze/A-12a.png",
        price: 150,
      },
      {
        id: 18,
        numer_znaku: "A-12b",
        name: "Zwężenie jezdni – prawostronne",
        obraz: "/images/ostrzegawcze/A-12b.png",
        price: 150,
      },
      {
        id: 19,
        numer_znaku: "A-12c",
        name: "Zwężenie jezdni – lewostronne",
        obraz: "/images/ostrzegawcze/A-12c.png",
        price: 150,
      },
      {
        id: 20,
        numer_znaku: "A-13",
        name: "Ruchomy most",
        obraz: "/images/ostrzegawcze/A-13.png",
        price: 150,
      },
      {
        id: 21,
        numer_znaku: "A-14",
        name: "Sygnalizacja świetlna",
        obraz: "/images/ostrzegawcze/A-14.png",
        price: 150,
      },
      {
        id: 22,
        numer_znaku: "A-15",
        name: "Śliska jezdnia",
        obraz: "/images/ostrzegawcze/A-15.png",
        price: 150,
      },
      {
        id: 23,
        numer_znaku: "A-16",
        name: "Przejście dla pieszych",
        obraz: "/images/ostrzegawcze/A-16.png",
        price: 150,
      },
      {
        id: 24,
        numer_znaku: "A-17",
        name: "Dzieci",
        obraz: "/images/ostrzegawcze/A-17.png",
        price: 150,
      },
      {
        id: 25,
        numer_znaku: "A-18a",
        name: "Zwierzęta gospodarskie",
        obraz: "/images/ostrzegawcze/A-18a.png",
        price: 150,
      },
      {
        id: 26,
        numer_znaku: "A-18b",
        name: "Zwierzęta dzikie",
        obraz: "/images/ostrzegawcze/A-18b.png",
        price: 150,
      },
      {
        id: 27,
        numer_znaku: "A-19",
        name: "Boczny wiatr",
        obraz: "/images/ostrzegawcze/A-19.png",
        price: 150,
      },
      {
        id: 28,
        numer_znaku: "A-20",
        name: "Odłamki skalne",
        obraz: "/images/ostrzegawcze/A-20.png",
        price: 150,
      },
      {
        id: 29,
        numer_znaku: "A-21",
        name: "Tramwaj",
        obraz: "/images/ostrzegawcze/A-21.png",
        price: 150,
      },
      {
        id: 30,
        numer_znaku: "A-22",
        name: "Niebezpieczny zjazd",
        obraz: "/images/ostrzegawcze/A-22.png",
        price: 150,
      },
      {
        id: 31,
        numer_znaku: "A-23",
        name: "Rowerzyści",
        obraz: "/images/ostrzegawcze/A-23.png",
        price: 150,
      },
      {
        id: 32,
        numer_znaku: "A-24",
        name: "Roboty na drodze",
        obraz: "/images/ostrzegawcze/A-24.png",
        price: 150,
      },
    ],
  },
  {
    title: "Znaki dodatkowe",
    items: [
      {
        id: 33,
        numer_znaku: "G-1a",
        name: "Informuje o zbliżaniu się do przejazdu kolejowego.",
        obraz: "/images/dodatkowe/G-1a.png",
        price: 100,
      },
      {
        id: 34,
        numer_znaku: "G-1b",
        name: "Informuje o zbliżaniu się do przejazdu kolejowego.",
        obraz: "/images/dodatkowe/G-1b.png",
        price: 100,
      },
      {
        id: 35,
        numer_znaku: "G-1c",
        name: "Informuje o zbliżaniu się do przejazdu kolejowego.",
        obraz: "/images/dodatkowe/G-1c.png",
        price: 100,
      },
      {
        id: 36,
        numer_znaku: "G-1d",
        name: "Informuje o zbliżaniu się do przejazdu kolejowego.",
        obraz: "/images/dodatkowe/G-1d.png",
        price: 100,
      },
      {
        id: 37,
        numer_znaku: "G-1e",
        name: "Informuje o zbliżaniu się do przejazdu kolejowego.",
        obraz: "/images/dodatkowe/G-1e.png",
        price: 100,
      },
      {
        id: 38,
        numer_znaku: "G-01f",
        name: "Informuje o zbliżaniu się do przejazdu kolejowego.",
        obraz: "/images/dodatkowe/G-01f.png",
        price: 100,
      },
      {
        id: 39,
        numer_znaku: "G-2",
        name: "Oznacza, że nad przejazdem kolejowym zawieszona jest sieć trakcyjna.",
        obraz: "/images/dodatkowe/G-2.png",
        price: 100,
      },
      {
        id: 40,
        numer_znaku: "G-3",
        name: "Wyznacza miejsce zatrzymania się w związku z ruchem pociągu lub innego pojazdu szynowego na przejeździe kolejowym bez zapór lub półzapór.",
        obraz: "/images/dodatkowe/G-3.png",
        price: 100,
      },
      {
        id: 41,
        numer_znaku: "G-4",
        name: "Wyznacza miejsce zatrzymania się w związku z ruchem pociągu lub innego pojazdu szynowego na przejeździe kolejowym bez zapór lub półzapór.",
        obraz: "/images/dodatkowe/G-4.png",
        price: 100,
      },
    ],
  },
  {
    title: "Znaki zakazu",
    items: [
      {
        id: 42,
        numer_znaku: "B-1",
        name: "Zakaz ruchu w obu kierunkach",
        obraz: "/images/zakazu/B-1.png",
        price: 100,
      },
      {
        id: 43,
        numer_znaku: "B-2",
        name: "Zakaz wjazdu",
        obraz: "/images/zakazu/B-2.png",
        price: 100,
      },
      {
        id: 44,
        numer_znaku: "B-3",
        name: "Zakaz wjazdu poj. silnikowych (bez motocykli jednośladowych)",
        obraz: "/images/zakazu/B-3.png",
        price: 100,
      },
      {
        id: 45,
        numer_znaku: "B-3a",
        name: "Zakaz wjazdu autobusów",
        obraz: "/images/zakazu/B-3a.png",
        price: 100,
      },
      {
        id: 46,
        numer_znaku: "B-4",
        name: "Zakaz wjazdu motocykli",
        obraz: "/images/zakazu/B-4.png",
        price: 100,
      },
      {
        id: 47,
        numer_znaku: "B-5",
        name: "Zakaz wjazdu samochodów ciężarowych",
        obraz: "/images/zakazu/B-5.png",
        price: 100,
      },
      {
        id: 48,
        numer_znaku: "B-6",
        name: "Zakaz wjazdu ciągników rolniczych",
        obraz: "/images/zakazu/B-6.png",
        price: 100,
      },
      {
        id: 49,
        numer_znaku: "B-7",
        name: "Zakaz wjazdu pojazdów z przyczepą",
        obraz: "/images/zakazu/B-7.png",
        price: 100,
      },
      {
        id: 50,
        numer_znaku: "B-8",
        name: "Zakaz wjazdu pojazdów zaprzęgowych",
        obraz: "/images/zakazu/B-8.png",
        price: 100,
      },
      {
        id: 51,
        numer_znaku: "B-9",
        name: "Zakaz wjazdu rowerów",
        obraz: "/images/zakazu/B-9.png",
        price: 100,
      },
      {
        id: 52,
        numer_znaku: "B-10",
        name: "Zakaz wjazdu motorowerów",
        obraz: "/images/zakazu/B-10.png",
        price: 100,
      },
      {
        id: 53,
        numer_znaku: "B-11",
        name: "Zakaz wjazdu wózków rowerowych i rowerów wielośladowych",
        obraz: "/images/zakazu/B-11.png",
        price: 100,
      },
      {
        id: 54,
        numer_znaku: "B-12",
        name: "Zakaz wjazdu wózków ręcznych",
        obraz: "/images/zakazu/B-12.png",
        price: 100,
      },
      {
        id: 55,
        numer_znaku: "B-13",
        name: "Zakaz pojazdów z materiałami wybuchowymi lub łatwopalnymi",
        obraz: "/images/zakazu/B-13.png",
        price: 100,
      },
      {
        id: 56,
        numer_znaku: "B-13a",
        name: "Zakaz pojazdów z materiałami niebezpiecznymi",
        obraz: "/images/zakazu/B-13.png",
        price: 100,
      },
      {
        id: 57,
        numer_znaku: "B-14",
        name: "Zakaz pojazdów mogących skazić wodę",
        obraz: "/images/zakazu/B-14.png",
        price: 100,
      },
      {
        id: 58,
        numer_znaku: "B-15",
        name: "Zakaz pojazdów szerszych niż ... m",
        obraz: "/images/zakazu/B-15.png",
        price: 100,
      },
      {
        id: 59,
        numer_znaku: "B-16",
        name: "Zakaz pojazdów wyższych niż ... m",
        obraz: "/images/zakazu/B-16.png",
        price: 100,
      },
      {
        id: 60,
        numer_znaku: "B-17",
        name: "Zakaz pojazdów dłuższych niż ... m",
        obraz: "/images/zakazu/B-17.png",
        price: 100,
      },
      {
        id: 61,
        numer_znaku: "B-18",
        name: "Zakaz pojazdów cięższych niż ... t",
        obraz: "/images/zakazu/B-18.png",
        price: 100,
      },
      {
        id: 62,
        numer_znaku: "B-19",
        name: "Zakaz nacisku osi większego niż ... t",
        obraz: "/images/zakazu/B-19.png",
        price: 100,
      },
      {
        id: 63,
        numer_znaku: "B-20",
        name: "STOP",
        obraz: "/images/zakazu/B-20.png",
        price: 100,
      },
      {
        id: 64,
        numer_znaku: "B-21",
        name: "Zakaz skrętu w lewo",
        obraz: "/images/zakazu/B-21.png",
        price: 100,
      },
      {
        id: 65,
        numer_znaku: "B-22",
        name: "Zakaz skrętu w prawo",
        obraz: "/images/zakazu/B-22.png",
        price: 100,
      },
      {
        id: 66,
        numer_znaku: "B-23",
        name: "Zakaz zawracania",
        obraz: "/images/zakazu/B-23.png",
        price: 100,
      },
      {
        id: 67,
        numer_znaku: "B-24",
        name: "Koniec zakazu zawracania",
        obraz: "/images/zakazu/B-24.png",
        price: 100,
      },
      {
        id: 68,
        numer_znaku: "B-25",
        name: "Zakaz wyprzedzania",
        obraz: "/images/zakazu/B-25.png",
        price: 100,
      },
      {
        id: 69,
        numer_znaku: "B-26",
        name: "Zakaz wyprzedzania przez ciężarówki",
        obraz: "/images/zakazu/B-26.png",
        price: 100,
      },
      {
        id: 70,
        numer_znaku: "B-27",
        name: "Koniec zakazu wyprzedzania",
        obraz: "/images/zakazu/B-27.png",
        price: 100,
      },
      {
        id: 71,
        numer_znaku: "B-28",
        name: "Koniec zakazu wyprzedzania przez ciężarówki",
        obraz: "/images/zakazu/B-28.png",
        price: 100,
      },
      {
        id: 72,
        numer_znaku: "B-29",
        name: "Zakaz sygnałów dźwiękowych",
        obraz: "/images/zakazu/B-29.png",
        price: 100,
      },
      {
        id: 73,
        numer_znaku: "B-30",
        name: "Koniec zakazu sygnałów dźwiękowych",
        obraz: "/images/zakazu/B-30.png",
        price: 100,
      },
      {
        id: 74,
        numer_znaku: "B-31",
        name: "Pierwszeństwo dla nadjeżdżających z przeciwka",
        obraz: "/images/zakazu/B-31.png",
        price: 100,
      },
      {
        id: 75,
        numer_znaku: "B-32",
        name: "Stój – kontrola",
        obraz: "/images/zakazu/B-32.png",
        price: 100,
      },
      {
        id: 76,
        numer_znaku: "B-33",
        name: "Ograniczenie prędkości",
        obraz: "/images/zakazu/B-33.png",
        price: 100,
      },
      {
        id: 77,
        numer_znaku: "B-34",
        name: "Koniec ograniczenia prędkości",
        obraz: "/images/zakazu/B-34.png",
        price: 100,
      },
      {
        id: 78,
        numer_znaku: "B-35",
        name: "Zakaz postoju",
        obraz: "/images/zakazu/B-35.png",
        price: 100,
      },
      {
        id: 79,
        numer_znaku: "B-36",
        name: "Zakaz zatrzymywania się",
        obraz: "/images/zakazu/B-36.png",
        price: 100,
      },
    ],
  },
  {
    title: "Znaki nakazu",
    items: [
      {
        id: 80,
        numer_znaku: "C-1",
        name: "Nakaz jazdy w prawo przed znakiem",
        obraz: "/images/nakazu/C-1.png",
        price: 100,
      },
      {
        id: 81,
        numer_znaku: "C-2",
        name: "Nakaz jazdy w prawo za znakiem",
        obraz: "/images/nakazu/C-2.png",
        price: 100,
      },
      {
        id: 82,
        numer_znaku: "C-3",
        name: "Nakaz jazdy w lewo przed znakiem",
        obraz: "/images/nakazu/C-3.png",
        price: 100,
      },
      {
        id: 83,
        numer_znaku: "C-4",
        name: "Nakaz jazdy w lewo za znakiem",
        obraz: "/images/nakazu/C-4.png",
        price: 100,
      },
      {
        id: 84,
        numer_znaku: "C-5",
        name: "Nakaz jazdy prosto",
        obraz: "/images/nakazu/C-5.png",
        price: 100,
      },
      {
        id: 85,
        numer_znaku: "C-6",
        name: "Nakaz jazdy prosto lub w prawo",
        obraz: "/images/nakazu/C-6.png",
        price: 100,
      },
      {
        id: 86,
        numer_znaku: "C-7",
        name: "Nakaz jazdy prosto lub w lewo",
        obraz: "/images/nakazu/C-7.png",
        price: 100,
      },
      {
        id: 87,
        numer_znaku: "C-8",
        name: "Nakaz jazdy w prawo lub w lewo",
        obraz: "/images/nakazu/C-8.png",
        price: 100,
      },
      {
        id: 88,
        numer_znaku: "C-9",
        name: "Nakaz jazdy z prawej strony znaku",
        obraz: "/images/nakazu/C-9.png",
        price: 100,
      },
      {
        id: 89,
        numer_znaku: "C-10",
        name: "Nakaz jazdy z lewej strony znaku",
        obraz: "/images/nakazu/C-10.png",
        price: 100,
      },
      {
        id: 90,
        numer_znaku: "C-11",
        name: "Nakaz jazdy z prawej lub z lewej strony znaku",
        obraz: "/images/nakazu/C-11.png",
        price: 100,
      },
      {
        id: 91,
        numer_znaku: "C-12",
        name: "Ruch okrężny",
        obraz: "/images/nakazu/C-12.png",
        price: 100,
      },
      {
        id: 92,
        numer_znaku: "C-13",
        name: "Droga dla rowerów",
        obraz: "/images/nakazu/C-13.png",
        price: 100,
      },
      {
        id: 93,
        numer_znaku: "C-13a",
        name: "Koniec drogi dla rowerów",
        obraz: "/images/nakazu/C-13a.png",
        price: 100,
      },
      {
        id: 94,
        numer_znaku: "C-14",
        name: "Prędkość minimalna",
        obraz: "/images/nakazu/C-14.png",
        price: 100,
      },
      {
        id: 95,
        numer_znaku: "C-15",
        name: "Koniec minimalnej prędkości",
        obraz: "/images/nakazu/C-15.png",
        price: 100,
      },
      {
        id: 96,
        numer_znaku: "C-16",
        name: "Droga dla pieszych",
        obraz: "/images/nakazu/C-16.png",
        price: 100,
      },
      {
        id: 97,
        numer_znaku: "C-16a",
        name: "Koniec drogi dla pieszych",
        obraz: "/images/nakazu/C-16a.png",
        price: 100,
      },
      {
        id: 98,
        numer_znaku: "C-17",
        name: "Nakazany kierunek jazdy dla pojazdów z materiałami niebezpiecznymi",
        obraz: "/images/nakazu/C-17.png",
        price: 100,
      },
      {
        id: 99,
        numer_znaku: "C-18",
        name: "Nakaz używania łańcuchów przeciwpoślizgowych",
        obraz: "/images/nakazu/C-18.png",
        price: 100,
      },
      {
        id: 100,
        numer_znaku: "C-19",
        name: "Koniec nakazu używania łańcuchów przeciwpoślizgowych",
        obraz: "/images/nakazu/C-19.png",
        price: 100,
      },
    ],
  },
  {
    title: "Znaki uzupełniajace",
    items: [
      {
        id: 101,
        numer_znaku: "F-1",
        name: "Przejście graniczne",
        obraz: "/images/uzupelniajace/F-1.png",
        price: 100,
      },
      {
        id: 102,
        numer_znaku: "F-2",
        name: "Przekraczanie granicy zabronione",
        obraz: "/images/uzupelniajace/F-2.png",
        price: 100,
      },
      {
        id: 103,
        numer_znaku: "F-2a",
        name: "Granica państwa",
        obraz: "/images/uzupelniajace/F-2a.png",
        price: 100,
      },
      {
        id: 104,
        numer_znaku: "F-3",
        name: "Granica obszaru administracyjnego",
        obraz: "/images/uzupelniajace/F-3.png",
        price: 100,
      },
      {
        id: 105,
        numer_znaku: "F-4",
        name: "Nazwa rzeki",
        obraz: "/images/uzupelniajace/F-4.png",
        price: 100,
      },
      {
        id: 106,
        numer_znaku: "F-5",
        name: "Uprzedzenie o zakazie",
        obraz: "/images/uzupelniajace/F-5.png",
        price: 100,
      },
      {
        id: 107,
        numer_znaku: "F-6",
        name: "Znak uprzedzający, umieszczany przed skrzyżowaniem",
        obraz: "/images/uzupelniajace/F-6.png",
        price: 100,
      },
      {
        id: 108,
        numer_znaku: "F-7",
        name: "Sposób jazdy w związku z zakazem skręcania w lewo",
        obraz: "/images/uzupelniajace/F-7.gif",
        price: 100,
      },
      {
        id: 109,
        numer_znaku: "F-8",
        name: "Objazd w związku z zamknięciem drogi",
        obraz: "/images/uzupelniajace/F-8.png",
        price: 100,
      },
      {
        id: 110,
        numer_znaku: "F-9",
        name: "Znak prowadzący na drodze objazdowej",
        obraz: "/images/uzupelniajace/F-9.png",
        price: 100,
      },
      {
        id: 111,
        numer_znaku: "F-10",
        name: "Kierunki na pasach ruchu",
        obraz: "/images/uzupelniajace/F-10.png",
        price: 100,
      },
      {
        id: 112,
        numer_znaku: "F-11",
        name: "Kierunki na pasie ruchu",
        obraz: "/images/uzupelniajace/F-11.png",
        price: 100,
      },
      {
        id: 113,
        numer_znaku: "F-12",
        name: "Znak wskazujący przejazd tranzytowy umieszczany przed skrzyżowaniem",
        obraz: "/images/uzupelniajace/F-12.png",
        price: 100,
      },
      {
        id: 114,
        numer_znaku: "F-13",
        name: "Przejazd tranzytowy",
        obraz: "/images/uzupelniajace/F-13.png",
        price: 100,
      },
      {
        id: 115,
        numer_znaku: "F-14a",
        name: "Tablica wskaźnikowa na autostradzie umieszczana w odległości 300 m przed pasem wyłączania",
        obraz: "/images/uzupelniajace/F-14a.png",
        price: 100,
      },
      {
        id: 116,
        numer_znaku: "F-14b",
        name: "Tablica wskaźnikowa na autostradzie umieszczana w odległości 200 m przed pasem wyłączania",
        obraz: "/images/uzupelniajace/F-14b.png",
        price: 100,
      },
      {
        id: 117,
        numer_znaku: "F-14c",
        name: "Tablica wskaźnikowa na autostradzie umieszczana w odległości 100 m przed pasem wyłączania",
        obraz: "/images/uzupelniajace/F-14c.png",
        price: 100,
      },
      {
        id: 118,
        numer_znaku: "F-15",
        name: "Niesymetryczny podział jezdni dla przeciwnych kierunków ruchu",
        obraz: "/images/uzupelniajace/F-15.png",
        price: 100,
      },
      {
        id: 119,
        numer_znaku: "F-16",
        name: "Koniec pasa ruchu na jezdni dwukierunkowej",
        obraz: "/images/uzupelniajace/F-16.png",
        price: 100,
      },
      {
        id: 120,
        numer_znaku: "F-17",
        name: "Koniec pasa ruchu na jezdni jednokierunkowej",
        obraz: "/images/uzupelniajace/F-17.png",
        price: 100,
      },
      {
        id: 121,
        numer_znaku: "F-18",
        name: "Przeciwny kierunek dla określonych pojazdów",
        obraz: "/images/uzupelniajace/F-18.gif",
        price: 100,
      },
      {
        id: 122,
        numer_znaku: "F-19",
        name: "Pas ruchu dla określonych pojazdów",
        obraz: "/images/uzupelniajace/F-19.png",
        price: 100,
      },
      {
        id: 123,
        numer_znaku: "F-20",
        name: "Część drogi (pas ruchu) dla określonych pojazdów",
        obraz: "/images/uzupelniajace/F-20.png",
        price: 100,
      },
      {
        id: 124,
        numer_znaku: "F-21",
        name: "Ruch skierowany na sąsiednią jezdnię",
        obraz: "/images/uzupelniajace/F-21.png",
        price: 100,
      },
      {
        id: 125,
        numer_znaku: "F-22",
        name: "Ograniczenia na pasie ruchu",
        obraz: "/images/uzupelniajace/F-22.png",
        price: 100,
      },
    ],
  },
  {
    title: "Znaki kierunku i miejscowości",
    items: [
      {
        id: 200,
        numer_znaku: "E-1",
        name: "Tablica przeddrogowskazowa",
        obraz: "/images/kierunku_i_miejscowosci/E-1.png",
        price: 100,
      },
      {
        id: 201,
        numer_znaku: "E-1a",
        name: "Tablica przeddrogowskazowa na autostradzie",
        obraz: "/images/kierunku_i_miejscowosci/E-1a.png",
        price: 100,
      },
      {
        id: 202,
        numer_znaku: "E-1b",
        name: "Tablica przeddrogowskazowa przed wjazdem na autostradę",
        obraz: "/images/kierunku_i_miejscowosci/E-1b.png",
        price: 100,
      },
      {
        id: 203,
        numer_znaku: "E-2a",
        name: "Drogowskaz tablicowy umieszczany obok jezdni",
        obraz: "/images/kierunku_i_miejscowosci/E-2a.png",
        price: 100,
      },
      {
        id: 204,
        numer_znaku: "E-2b",
        name: "Drogowskaz tablicowy umieszczany nad jezdnią",
        obraz: "/images/kierunku_i_miejscowosci/E-2b.png",
        price: 100,
      },
      {
        id: 205,
        numer_znaku: "E-2c",
        name: "Drogowskaz tablicowy umieszczany nad jezdnią na autostradzie",
        obraz: "/images/kierunku_i_miejscowosci/E-2c.png",
        price: 100,
      },
      {
        id: 206,
        numer_znaku: "E-2d",
        name: "Drogowskaz tablicowy umieszczany nad jezdnią na autostradzie",
        obraz: "/images/kierunku_i_miejscowosci/E-2d.png",
        price: 100,
      },
      {
        id: 207,
        numer_znaku: "E-2e",
        name: "Drogowskaz tablicowy umieszczany przed wjazdem na autostradę",
        obraz: "/images/kierunku_i_miejscowosci/E-2e.png",
        price: 100,
      },
      {
        id: 208,
        numer_znaku: "E-2f",
        name: "Drogowskaz tablicowy umieszczany nad jezdnią przed wjazdem na autostradę",
        obraz: "/images/kierunku_i_miejscowosci/E-2f.png",
        price: 100,
      },
      {
        id: 209,
        numer_znaku: "E-3",
        name: "Drogowskaz w kształcie strzały do miejscowości wskazujący numer drogi",
        obraz: "/images/kierunku_i_miejscowosci/E-3.png",
        price: 100,
      },
      {
        id: 210,
        numer_znaku: "E-4",
        name: "Drogowskaz w kształcie strzały do miejscowości, podający odległość do niej",
        obraz: "/images/kierunku_i_miejscowosci/E-4.png",
        price: 100,
      },
      {
        id: 211,
        numer_znaku: "E-5",
        name: "Drogowskaz do dzielnicy miasta",
        obraz: "/images/kierunku_i_miejscowosci/E-5.png",
        price: 100,
      },
      {
        id: 212,
        numer_znaku: "E-6",
        name: "Drogowskaz do lotniska",
        obraz: "/images/kierunku_i_miejscowosci/E-6.png",
        price: 100,
      },
      {
        id: 213,
        numer_znaku: "E-6a",
        name: "Drogowskaz do dworca lub stacji kolejowej",
        obraz: "/images/kierunku_i_miejscowosci/E-6a.png",
        price: 100,
      },
      {
        id: 214,
        numer_znaku: "E-6b",
        name: "Drogowskaz do dworca autobusowego",
        obraz: "/images/kierunku_i_miejscowosci/E-6b.png",
        price: 100,
      },
      {
        id: 215,
        numer_znaku: "E-6c",
        name: "Drogowskaz do przystani promowej",
        obraz: "/images/kierunku_i_miejscowosci/E-6c.png",
        price: 100,
      },
      {
        id: 216,
        numer_znaku: "E-7",
        name: "Drogowskaz do przystani wodnej lub żeglugi",
        obraz: "/images/kierunku_i_miejscowosci/E-7.png",
        price: 100,
      },
      {
        id: 217,
        numer_znaku: "E-8",
        name: "Drogowskaz do plaży lub miejsca kąpielowego",
        obraz: "/images/kierunku_i_miejscowosci/E-8.png",
        price: 100,
      },
      {
        id: 218,
        numer_znaku: "E-9",
        name: "Drogowskaz do muzeum",
        obraz: "/images/kierunku_i_miejscowosci/E-9.png",
        price: 100,
      },
      {
        id: 219,
        numer_znaku: "E-10",
        name: "Drogowskaz do zabytku jako dobra kultury",
        obraz: "/images/kierunku_i_miejscowosci/E-10.png",
        price: 100,
      },
      {
        id: 220,
        numer_znaku: "E-11",
        name: "Drogowskaz do zabytku przyrody",
        obraz: "/images/kierunku_i_miejscowosci/E-11.png",
        price: 100,
      },
      {
        id: 221,
        numer_znaku: "E-12",
        name: "Drogowskaz do punktu widokowego",
        obraz: "/images/kierunku_i_miejscowosci/E-12.png",
        price: 100,
      },
      {
        id: 222,
        numer_znaku: "E-12a",
        name: "Drogowskaz do szlaku rowerowego",
        obraz: "/images/kierunku_i_miejscowosci/E-12a.png",
        price: 100,
      },
      {
        id: 223,
        numer_znaku: "E-13",
        name: "Tablica kierunkowa",
        obraz: "/images/kierunku_i_miejscowosci/E-13.png",
        price: 100,
      },
      {
        id: 224,
        numer_znaku: "E-14",
        name: "Tablica szlaku drogowego",
        obraz: "/images/kierunku_i_miejscowosci/E-14.png",
        price: 100,
      },
      {
        id: 225,
        numer_znaku: "E-14a",
        name: "Tablica szlaku drogowego przy autostradzie",
        obraz: "/images/kierunku_i_miejscowosci/E-14a.png",
        price: 100,
      },
      {
        id: 226,
        numer_znaku: "E-15a",
        name: "Numer drogi krajowej",
        obraz: "/images/kierunku_i_miejscowosci/E-15.png",
        price: 100,
      },
      {
        id: 227,
        numer_znaku: "E-15b",
        name: "Numer drogi wojewódzkiej",
        obraz: "/images/kierunku_i_miejscowosci/E-15b.png",
        price: 100,
      },
      {
        id: 228,
        numer_znaku: "E-15c",
        name: "Numer autostrady",
        obraz: "/images/kierunku_i_miejscowosci/E-15c.png",
        price: 100,
      },
      {
        id: 229,
        numer_znaku: "E-15d",
        name: "Numer drogi ekspresowej",
        obraz: "/images/kierunku_i_miejscowosci/E-15d.png",
        price: 100,
      },
      {
        id: 230,
        numer_znaku: "E-15e",
        name: "Numer drogi wojewódzkiej o zwiększonym do 10t dopuszczalnym nacisku osi pojazdu",
        obraz: "/images/kierunku_i_miejscowosci/E-15e.png",
        price: 100,
      },
      {
        id: 231,
        numer_znaku: "E-15f",
        name: "Nr drogi krajowej o dopuszczalnym nacisku osi pojazdu do 10t",
        obraz: "/images/kierunku_i_miejscowosci/E-15f.png",
        price: 100,
      },
      {
        id: 232,
        numer_znaku: "E-15g",
        name: "Nr drogi krajowej o dopuszczalnym nacisku osi pojazdu do 8t",
        obraz: "/images/kierunku_i_miejscowosci/E-15g.png",
        price: 100,
      },
      {
        id: 233,
        numer_znaku: "E-16",
        name: "Numer szlaku międzynarodowego",
        obraz: "/images/kierunku_i_miejscowosci/E-16.png",
        price: 100,
      },
      {
        id: 234,
        numer_znaku: "E-17",
        name: "Miejscowość",
        obraz: "/images/kierunku_i_miejscowosci/E-17.png",
        price: 100,
      },
      {
        id: 235,
        numer_znaku: "E-18a",
        name: "Koniec miejscowości",
        obraz: "/images/kierunku_i_miejscowosci/E-18.png",
        price: 100,
      },
      {
        id: 236,
        numer_znaku: "E-19a",
        name: "Obwodnica",
        obraz: "/images/kierunku_i_miejscowosci/E-19.png",
        price: 100,
      },
      {
        id: 237,
        numer_znaku: "E-20",
        name: "Tablica węzła drogowego na autostradzie",
        obraz: "/images/kierunku_i_miejscowosci/E-20.png",
        price: 100,
      },
      {
        id: 238,
        numer_znaku: "E-21",
        name: "Dzielnica (osiedle)",
        obraz: "/images/kierunku_i_miejscowosci/E-21.png",
        price: 100,
      },
      {
        id: 239,
        numer_znaku: "E-22a",
        name: "Samochodowy szlak turystyczny",
        obraz: "/images/kierunku_i_miejscowosci/E-22.png",
        price: 100,
      },
      {
        id: 240,
        numer_znaku: "E-22b",
        name: "Obiekt na samochodowym szlaku turystycznym",
        obraz: "/images/kierunku_i_miejscowosci/E-22b.png",
        price: 100,
      },
      {
        id: 241,
        numer_znaku: "E-22c",
        name: "Informacja o obiektach turystycznych",
        obraz: "/images/kierunku_i_miejscowosci/E-22c.png",
        price: 100,
      },
    ],
  },
  {
    title: "Znaki informacyjne",
    items: [
      {
        id: 242,
        numer_znaku: "D-1",
        name: "Droga z pierwszeństwem",
        obraz: "/images/informacyjne/D-1.png",
        price: 100,
      },
      {
        id: 243,
        numer_znaku: "D-2",
        name: "Koniec drogi z pierwszeństwem",
        obraz: "/images/informacyjne/D-2.png",
        price: 100,
      },
      {
        id: 244,
        numer_znaku: "D-3",
        name: "Droga jednokierunkowa",
        obraz: "/images/informacyjne/D-3.png",
        price: 100,
      },
      {
        id: 245,
        numer_znaku: "D-4a",
        name: "Droga bez przejazdu",
        obraz: "/images/informacyjne/D-4a.png",
        price: 100,
      },
      {
        id: 246,
        numer_znaku: "D-4b",
        name: "Wjazd na drogę bez przejazdu",
        obraz: "/images/informacyjne/D-4b.png",
        price: 100,
      },
      {
        id: 247,
        numer_znaku: "D-5",
        name: "Pierwszeństwo na zwężonym odcinku jezdni",
        obraz: "/images/informacyjne/D-5.png",
        price: 100,
      },
      {
        id: 248,
        numer_znaku: "D-6",
        name: "Przejście dla pieszych",
        obraz: "/images/informacyjne/D-6.png",
        price: 100,
      },
      {
        id: 249,
        numer_znaku: "D-6a",
        name: "Przejazd dla rowerów",
        obraz: "/images/informacyjne/D-6a.png",
        price: 100,
      },
      {
        id: 250,
        numer_znaku: "D-6b",
        name: "Przejście dla pieszych i przejazd dla rowerzystów",
        obraz: "/images/informacyjne/D-6b.png",
        price: 100,
      },
      {
        id: 251,
        numer_znaku: "D-7",
        name: "Droga ekspresowa",
        obraz: "/images/informacyjne/D-7.png",
        price: 100,
      },
      {
        id: 252,
        numer_znaku: "D-8",
        name: "Koniec drogi ekspresowej",
        obraz: "/images/informacyjne/D-8.png",
        price: 100,
      },
      {
        id: 253,
        numer_znaku: "D-9",
        name: "Autostrada",
        obraz: "/images/informacyjne/D-9.png",
        price: 100,
      },
      {
        id: 254,
        numer_znaku: "D-10",
        name: "Koniec autostrady",
        obraz: "/images/informacyjne/D-10.png",
        price: 100,
      },
      {
        id: 255,
        numer_znaku: "D-11",
        name: "Początek pasa ruchu dla autobusów",
        obraz: "/images/informacyjne/D-11.png",
        price: 100,
      },
      {
        id: 256,
        numer_znaku: "D-12",
        name: "Pas ruchu dla autobusów",
        obraz: "/images/informacyjne/D-12.png",
        price: 100,
      },
      {
        id: 257,
        numer_znaku: "D-13",
        name: "Początek pasa ruchu powolnego",
        obraz: "/images/informacyjne/D-13.png",
        price: 100,
      },
      {
        id: 258,
        numer_znaku: "D-13a",
        name: "Początek pasa ruchu",
        obraz: "/images/informacyjne/D-13a.png",
        price: 100,
      },
      {
        id: 259,
        numer_znaku: "D-14",
        name: "Koniec pasa ruchu",
        obraz: "/images/informacyjne/D-14.png",
        price: 100,
      },
      {
        id: 260,
        numer_znaku: "D-15",
        name: "Przystanek autobusowy",
        obraz: "/images/informacyjne/D-15.png",
        price: 100,
      },
      {
        id: 261,
        numer_znaku: "D-16",
        name: "Przystanek trolejbusowy",
        obraz: "/images/informacyjne/D-16.png",
        price: 100,
      },
      {
        id: 262,
        numer_znaku: "D-17",
        name: "Przystanek tramwajowy",
        obraz: "/images/informacyjne/D-17.png",
        price: 100,
      },
      {
        id: 263,
        numer_znaku: "D-18",
        name: "Parking",
        obraz: "/images/informacyjne/D-18.png",
        price: 100,
      },
      {
        id: 264,
        numer_znaku: "D-18a",
        name: "Parking - miejsce zastrzeżone",
        obraz: "/images/informacyjne/D-18a.png",
        price: 100,
      },
      {
        id: 265,
        numer_znaku: "D-18b",
        name: "Parking zadaszony",
        obraz: "/images/informacyjne/D-18b.png",
        price: 100,
      },
      {
        id: 266,
        numer_znaku: "D-19",
        name: "Postój taksówek",
        obraz: "/images/informacyjne/D-19.png",
        price: 100,
      },
      {
        id: 267,
        numer_znaku: "D-20",
        name: "Koniec postoju taksówek",
        obraz: "/images/informacyjne/D-20.png",
        price: 100,
      },
      {
        id: 268,
        numer_znaku: "D-21",
        name: "Szpital",
        obraz: "/images/informacyjne/D-21.png",
        price: 100,
      },
      {
        id: 269,
        numer_znaku: "D-21a",
        name: "Policja",
        obraz: "/images/informacyjne/D-21a.png",
        price: 100,
      },
      {
        id: 270,
        numer_znaku: "D-22",
        name: "Punkt opatrunkowy",
        obraz: "/images/informacyjne/D-22.png",
        price: 100,
      },
      {
        id: 271,
        numer_znaku: "D-23",
        name: "Stacja paliwowa",
        obraz: "/images/informacyjne/D-23.png",
        price: 100,
      },
      {
        id: 272,
        numer_znaku: "D-23a",
        name: "Stacja paliwowa tylko z gazem do napędu pojazdów",
        obraz: "/images/informacyjne/D-23a.png",
        price: 100,
      },
      {
        id: 273,
        numer_znaku: "D-24",
        name: "Telefon",
        obraz: "/images/informacyjne/D-24.png",
        price: 100,
      },
      {
        id: 274,
        numer_znaku: "D-25",
        name: "Poczta",
        obraz: "/images/informacyjne/D-25.png",
        price: 100,
      },
      {
        id: 275,
        numer_znaku: "D-26",
        name: "Stacja obsługi technicznej",
        obraz: "/images/informacyjne/D-26.png",
        price: 100,
      },
      {
        id: 276,
        numer_znaku: "D-26a",
        name: "Wulkanizacja",
        obraz: "/images/informacyjne/D-26a.png",
        price: 100,
      },
      {
        id: 277,
        numer_znaku: "D-26b",
        name: "Myjnia",
        obraz: "/images/informacyjne/D-26b.png",
        price: 100,
      },
      {
        id: 278,
        numer_znaku: "D-26c",
        name: "Toaleta publiczna",
        obraz: "/images/informacyjne/D-26c.png",
        price: 100,
      },
      {
        id: 279,
        numer_znaku: "D-26d",
        name: "Natrysk",
        obraz: "/images/informacyjne/D-26d.png",
        price: 100,
      },
      {
        id: 280,
        numer_znaku: "D-27",
        name: "Bufet lub kawiarnia",
        obraz: "/images/informacyjne/D-27.png",
        price: 100,
      },
      {
        id: 281,
        numer_znaku: "D-28",
        name: "Restauracja",
        obraz: "/images/informacyjne/D-28.png",
        price: 100,
      },
      {
        id: 282,
        numer_znaku: "D-29",
        name: "Hotel (motel)",
        obraz: "/images/informacyjne/D-29.png",
        price: 100,
      },
      {
        id: 283,
        numer_znaku: "D-30",
        name: "Obozowisko (camping)",
        obraz: "/images/informacyjne/D-30.png",
        price: 100,
      },
      {
        id: 284,
        numer_znaku: "D-31",
        name: "Obozowisko (camping) z podłączeniem elektrycznym",
        obraz: "/images/informacyjne/D-31.png",
        price: 100,
      },
      {
        id: 285,
        numer_znaku: "D-32",
        name: "Pole biwakowe",
        obraz: "/images/informacyjne/D-32.png",
        price: 100,
      },
      {
        id: 286,
        numer_znaku: "D-33",
        name: "Schronisko młodzieżowe",
        obraz: "/images/informacyjne/D-33.png",
        price: 100,
      },
      {
        id: 287,
        numer_znaku: "D-34",
        name: "Punkt informacji turystycznej",
        obraz: "/images/informacyjne/D-34.png",
        price: 100,
      },
      {
        id: 288,
        numer_znaku: "D-34a",
        name: "Informacja radiowa o ruchu drogowym",
        obraz: "/images/informacyjne/D-34a.png",
        price: 100,
      },
      {
        id: 289,
        numer_znaku: "D-35",
        name: "Przejście podziemne dla pieszych",
        obraz: "/images/informacyjne/D-35.png",
        price: 100,
      },
      {
        id: 290,
        numer_znaku: "D-35a",
        name: "Schody ruchome w dół",
        obraz: "/images/informacyjne/D-35a.png",
        price: 100,
      },
      {
        id: 291,
        numer_znaku: "D-36",
        name: "Przejście nadziemne dla pieszych",
        obraz: "/images/informacyjne/D-36.png",
        price: 100,
      },
    ],
  },
];

export default SHOP_DATA;
